version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Build"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/Generator"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/Tests/Build.Tests"
    schedule:
      interval: "daily"
