name: 'Continuous integration'

on:
  workflow_dispatch:
  push:
    branches: 
      - develop
    paths-ignore:
      - 'README.md'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v2.3.4
        with: 
          submodules: 'true'

      - name: Prepare .NET
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: '5.0.x'

      - name: Run release build (unit tests)
        if: ${{ matrix.os == 'windows-latest' || matrix.os == 'macos-latest' }}
        run: dotnet run -- --release --xml-documentation --targets unitTest samples
        working-directory: './Build'

      - name: Run release build (integration tests)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: dotnet run -- --release --xml-documentation --targets integrationTest samples
        working-directory: './Build'
